name: Age Checker Workflow

on:
  push:
    branches:
      - test-branch  # Sadece test-branch üzerinde tetiklenir
    paths:
      - input.txt  # input.txt dosyasının yüklenmesiyle tetiklenir

jobs:
  process-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # PAT kullanarak checkout işlemi yapılacak

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install --upgrade pip

      - name: Run Age Checker Script
        run: |
          python main.py input.txt araliginiz.txt

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/ardatunali/finaldeneme2.git
          git add araliginiz.txt
          git commit -m "Add result for input age"
          git push origin test-branch
